"""login lockout fields

Revision ID: 3b225a030989
Revises: a5517b0a0fff
Create Date: 2026-09-05 16:12:55.038672
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (UTCDateTime) are rendered by autogenerate as fully
# qualified paths, so the module must be importable here.
import app.db.base  # noqa: F401


revision: str = '3b225a030989'
down_revision: Union[str, None] = 'a5517b0a0fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default is required: adding a NOT NULL column to a table that
        # already holds rows fails without one. It backfills existing users to 0.
        batch_op.add_column(
            sa.Column(
                'failed_login_attempts',
                sa.Integer(),
                nullable=False,
                server_default=sa.text('0'),
            )
        )
        batch_op.add_column(sa.Column('locked_until', app.db.base.UTCDateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
