"""initial schema

Revision ID: a5517b0a0fff
Revises: 
Create Date: 2026-09-05 16:10:41.391803
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.base  # noqa: F401


revision: str = 'a5517b0a0fff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'external_id', name='uq_account_external')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('context_sent', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.create_index('ix_ai_lookup', ['user_id', 'agent', 'input_fingerprint'], unique=False)
        batch_op.create_index('ix_ai_recent', ['user_id', 'agent', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_recommendations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_recommendations_user_id'), ['user_id'], unique=False)

    op.create_table('budget_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slug', name='uq_category_slug_per_user')
    )
    with op.batch_alter_table('budget_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_categories_user_id'), ['user_id'], unique=False)

    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('last_message_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_conversations_last_message_at'), ['last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('financial_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monthly_net_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_monthly_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('checking_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('savings_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('emergency_savings', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('investment_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_housing_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_essential_expenses', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_discretionary_expenses', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stated_total_debt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stated_debt_interest_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stated_minimum_payments', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('financial_goals', sa.JSON(), nullable=False),
    sa.Column('investment_horizon_years', sa.Integer(), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('onboarding_completed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('financial_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_expenses', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_cash_flow', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('savings_rate', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('emergency_fund_months', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('debt_to_income', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'captured_on', name='uq_snapshot_per_day')
    )
    with op.batch_alter_table('financial_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_snapshots_captured_on'), ['captured_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('monthly_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('expected_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_budget_period')
    )
    with op.batch_alter_table('monthly_budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_budgets_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('budget_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('budgeted_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['monthly_budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['budget_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'category_id', name='uq_budget_line')
    )
    with op.batch_alter_table('budget_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_lines_budget_id'), ['budget_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index('ix_chat_msg_convo', ['conversation_id', 'id'], unique=False)

    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('debt_type', sa.String(length=30), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('original_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('apr', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('minimum_payment', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debts_user_id'), ['user_id'], unique=False)

    op.create_table('investment_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('manual_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sector', sa.String(length=60), nullable=True),
    sa.Column('risk_category', sa.String(length=20), nullable=False),
    sa.Column('price_updated_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('price_source', sa.String(length=40), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment_holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_holdings_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_holdings_user_id'), ['user_id'], unique=False)

    op.create_table('savings_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('goal_type', sa.String(length=30), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('monthly_contribution', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('savings_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_goals_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('transfer_account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('merchant', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('txn_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['budget_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'external_id', name='uq_txn_external')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_occurred_on'), ['occurred_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_txn_user_date', ['user_id', 'occurred_on'], unique=False)
        batch_op.create_index('ix_txn_user_type_date', ['user_id', 'txn_type', 'occurred_on'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_user_type_date')
        batch_op.drop_index('ix_txn_user_date')
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_occurred_on'))
        batch_op.drop_index(batch_op.f('ix_transactions_external_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('savings_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_goals_user_id'))

    op.drop_table('savings_goals')
    with op.batch_alter_table('investment_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_holdings_user_id'))
        batch_op.drop_index(batch_op.f('ix_investment_holdings_ticker'))

    op.drop_table('investment_holdings')
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debts_user_id'))

    op.drop_table('debts')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_msg_convo')
        batch_op.drop_index(batch_op.f('ix_chat_messages_conversation_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('budget_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_lines_budget_id'))

    op.drop_table('budget_lines')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('monthly_budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_budgets_user_id'))

    op.drop_table('monthly_budgets')
    with op.batch_alter_table('financial_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_financial_snapshots_captured_on'))

    op.drop_table('financial_snapshots')
    with op.batch_alter_table('financial_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_profiles_user_id'))

    op.drop_table('financial_profiles')
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_conversations_last_message_at'))

    op.drop_table('chat_conversations')
    with op.batch_alter_table('budget_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_categories_user_id'))

    op.drop_table('budget_categories')
    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_created_at'))
        batch_op.drop_index('ix_ai_recent')
        batch_op.drop_index('ix_ai_lookup')

    op.drop_table('ai_recommendations')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_external_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
